//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace="tempuri.org")]

namespace tempuri.org
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DummyResponseType", Namespace="http://tempuri.org/")]
    public partial class DummyResponseType : object
    {
        
        private string appserverField;
        
        private string dbserverField;
        
        private string authserverField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appserver
        {
            get
            {
                return this.appserverField;
            }
            set
            {
                this.appserverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string dbserver
        {
            get
            {
                return this.dbserverField;
            }
            set
            {
                this.dbserverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authserver
        {
            get
            {
                return this.authserverField;
            }
            set
            {
                this.authserverField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credencial", Namespace="http://tempuri.org/")]
    public partial class Credencial : object
    {
        
        private string TokenField;
        
        private string SignField;
        
        private string CUITDelegadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Sign
        {
            get
            {
                return this.SignField;
            }
            set
            {
                this.SignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CUITDelegado
        {
            get
            {
                return this.CUITDelegadoField;
            }
            set
            {
                this.CUITDelegadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageResponse", Namespace="http://tempuri.org/")]
    public partial class MessageResponse : object
    {
        
        private string codigoField;
        
        private string descripcionField;
        
        private tempuri.org.PublicacionAPOC[] resultadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tempuri.org.PublicacionAPOC[] resultados
        {
            get
            {
                return this.resultadosField;
            }
            set
            {
                this.resultadosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicacionAPOC", Namespace="http://tempuri.org/")]
    public partial class PublicacionAPOC : object
    {
        
        private long CuitField;
        
        private string DescripcionField;
        
        private string FechaCondicionField;
        
        private string FechaPublicacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Cuit
        {
            get
            {
                return this.CuitField;
            }
            set
            {
                this.CuitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FechaCondicion
        {
            get
            {
                return this.FechaCondicionField;
            }
            set
            {
                this.FechaCondicionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FechaPublicacion
        {
            get
            {
                return this.FechaPublicacionField;
            }
            set
            {
                this.FechaPublicacionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service")]
public interface Service
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/Dummy", ReplyAction="*")]
    System.Threading.Tasks.Task<DummyResponse> DummyAsync(DummyRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetAll", ReplyAction="*")]
    System.Threading.Tasks.Task<GetAllResponse> GetAllAsync(GetAllRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetPublicacionAPOC", ReplyAction="*")]
    System.Threading.Tasks.Task<GetPublicacionAPOCResponse> GetPublicacionAPOCAsync(GetPublicacionAPOCRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetAllByPublicacion", ReplyAction="*")]
    System.Threading.Tasks.Task<GetAllByPublicacionResponse> GetAllByPublicacionAsync(GetAllByPublicacionRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DummyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="Dummy", Namespace="http://tempuri.org/", Order=0)]
    public DummyRequestBody Body;
    
    public DummyRequest()
    {
    }
    
    public DummyRequest(DummyRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class DummyRequestBody
{
    
    public DummyRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DummyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="DummyResponse", Namespace="http://tempuri.org/", Order=0)]
    public DummyResponseBody Body;
    
    public DummyResponse()
    {
    }
    
    public DummyResponse(DummyResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class DummyResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.DummyResponseType DummyResult;
    
    public DummyResponseBody()
    {
    }
    
    public DummyResponseBody(tempuri.org.DummyResponseType DummyResult)
    {
        this.DummyResult = DummyResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetAllRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
    public GetAllRequestBody Body;
    
    public GetAllRequest()
    {
    }
    
    public GetAllRequest(GetAllRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetAllRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.Credencial Credencial;
    
    public GetAllRequestBody()
    {
    }
    
    public GetAllRequestBody(tempuri.org.Credencial Credencial)
    {
        this.Credencial = Credencial;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetAllResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetAllResponseBody Body;
    
    public GetAllResponse()
    {
    }
    
    public GetAllResponse(GetAllResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetAllResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.MessageResponse GetAllResult;
    
    public GetAllResponseBody()
    {
    }
    
    public GetAllResponseBody(tempuri.org.MessageResponse GetAllResult)
    {
        this.GetAllResult = GetAllResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPublicacionAPOCRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPublicacionAPOC", Namespace="http://tempuri.org/", Order=0)]
    public GetPublicacionAPOCRequestBody Body;
    
    public GetPublicacionAPOCRequest()
    {
    }
    
    public GetPublicacionAPOCRequest(GetPublicacionAPOCRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetPublicacionAPOCRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.Credencial Credencial;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public long cuit;
    
    public GetPublicacionAPOCRequestBody()
    {
    }
    
    public GetPublicacionAPOCRequestBody(tempuri.org.Credencial Credencial, long cuit)
    {
        this.Credencial = Credencial;
        this.cuit = cuit;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPublicacionAPOCResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPublicacionAPOCResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetPublicacionAPOCResponseBody Body;
    
    public GetPublicacionAPOCResponse()
    {
    }
    
    public GetPublicacionAPOCResponse(GetPublicacionAPOCResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetPublicacionAPOCResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.MessageResponse GetPublicacionAPOCResult;
    
    public GetPublicacionAPOCResponseBody()
    {
    }
    
    public GetPublicacionAPOCResponseBody(tempuri.org.MessageResponse GetPublicacionAPOCResult)
    {
        this.GetPublicacionAPOCResult = GetPublicacionAPOCResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetAllByPublicacionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByPublicacion", Namespace="http://tempuri.org/", Order=0)]
    public GetAllByPublicacionRequestBody Body;
    
    public GetAllByPublicacionRequest()
    {
    }
    
    public GetAllByPublicacionRequest(GetAllByPublicacionRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetAllByPublicacionRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.Credencial Credencial;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string desde;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string hasta;
    
    public GetAllByPublicacionRequestBody()
    {
    }
    
    public GetAllByPublicacionRequestBody(tempuri.org.Credencial Credencial, string desde, string hasta)
    {
        this.Credencial = Credencial;
        this.desde = desde;
        this.hasta = hasta;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetAllByPublicacionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByPublicacionResponse", Namespace="http://tempuri.org/", Order=0)]
    public GetAllByPublicacionResponseBody Body;
    
    public GetAllByPublicacionResponse()
    {
    }
    
    public GetAllByPublicacionResponse(GetAllByPublicacionResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GetAllByPublicacionResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.MessageResponse GetAllByPublicacionResult;
    
    public GetAllByPublicacionResponseBody()
    {
    }
    
    public GetAllByPublicacionResponseBody(tempuri.org.MessageResponse GetAllByPublicacionResult)
    {
        this.GetAllByPublicacionResult = GetAllByPublicacionResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface ServiceChannel : Service, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<Service>, Service
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public ServiceClient(EndpointConfiguration endpointConfiguration) : 
            base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DummyResponse> Service.DummyAsync(DummyRequest request)
    {
        return base.Channel.DummyAsync(request);
    }
    
    public System.Threading.Tasks.Task<DummyResponse> DummyAsync()
    {
        DummyRequest inValue = new DummyRequest();
        inValue.Body = new DummyRequestBody();
        return ((Service)(this)).DummyAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetAllResponse> Service.GetAllAsync(GetAllRequest request)
    {
        return base.Channel.GetAllAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetAllResponse> GetAllAsync(tempuri.org.Credencial Credencial)
    {
        GetAllRequest inValue = new GetAllRequest();
        inValue.Body = new GetAllRequestBody();
        inValue.Body.Credencial = Credencial;
        return ((Service)(this)).GetAllAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetPublicacionAPOCResponse> Service.GetPublicacionAPOCAsync(GetPublicacionAPOCRequest request)
    {
        return base.Channel.GetPublicacionAPOCAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetPublicacionAPOCResponse> GetPublicacionAPOCAsync(tempuri.org.Credencial Credencial, long cuit)
    {
        GetPublicacionAPOCRequest inValue = new GetPublicacionAPOCRequest();
        inValue.Body = new GetPublicacionAPOCRequestBody();
        inValue.Body.Credencial = Credencial;
        inValue.Body.cuit = cuit;
        return ((Service)(this)).GetPublicacionAPOCAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetAllByPublicacionResponse> Service.GetAllByPublicacionAsync(GetAllByPublicacionRequest request)
    {
        return base.Channel.GetAllByPublicacionAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetAllByPublicacionResponse> GetAllByPublicacionAsync(tempuri.org.Credencial Credencial, string desde, string hasta)
    {
        GetAllByPublicacionRequest inValue = new GetAllByPublicacionRequest();
        inValue.Body = new GetAllByPublicacionRequestBody();
        inValue.Body.Credencial = Credencial;
        inValue.Body.desde = desde;
        inValue.Body.hasta = hasta;
        return ((Service)(this)).GetAllByPublicacionAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
            httpsBindingElement.AllowCookies = true;
            httpsBindingElement.MaxBufferSize = int.MaxValue;
            httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpsBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
        {
            return new System.ServiceModel.EndpointAddress("https://eapoc-ws.afip.gob.ar/service.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
        {
            return new System.ServiceModel.EndpointAddress("https://eapoc-ws.afip.gob.ar/service.asmx");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        ServiceSoap,
        
        ServiceSoap12,
    }
}
